### ISSUE TITLE
Error when entering more than $nnn,nnn,nnn.nn

### ISSUE THREAD

**Issue by rjpalermo1** [kaiomedau/realtime-currency-formatter-objc#2]
Just downloaded and ran sample, looks like there is something going in when entering into the hundred-thousand dollar range.  The numbers seem to be -1 of what is pressed/entered in that range.

For example pressing 5 up to $55,555.55 is fine, but press 5 again then output in textfield is $555,555.54.  Press 5 again then output is $5,555,555.33.  Press 5 again then output is $55,555,552.11

**Comment by heyvito** [comment]
Hi @rjpalermo1! Thanks for reporting this issue.

We noticed this a while ago, but we didn't have the time to fix it. 
Well, it should work fine now with values up to `90,071,992,547,409.90` (which is the maximum positive value a `double` supports before overflowing, and then causing this awkward behaviour you reported).

Please notice, however, that we are not limiting the input value.

I'll be closing this one, but feel free to open a new issue in case you find anything odd.

Thank you!
